name: Update Data from Google Sheets

on:
  schedule:
    - cron: '0 * * * *' # Будет запускаться автоматически каждый час
  workflow_dispatch: # Позволяет запускать обновление вручную кнопкой

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download fresh CSV
        run: |
          curl -Lo data.csv "https://google.com{{ secrets.GOOGLE_SHEET_ID }}/export?format=csv"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add data.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Автообновление данных" && git push)
